server:
  port: 9000
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    me.silvernine: debug